blank_issues_enabled: false
contact_links:
  - name: Security Reports
    url: https://github.com/bytemare/hash/security/advisories
    about: Please use GitHub Security Advisories for privately reporting vulnerabilities.
